// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB16wP8IXjr-8D0xDaixJ3H2DyG719X68',
    appId: '1:662297242127:web:0b9026915788655efed17a',
    messagingSenderId: '662297242127',
    projectId: 'lunastalaan',
    authDomain: 'lunastalaan.firebaseapp.com',
    storageBucket: 'lunastalaan.appspot.com',
    measurementId: 'G-L5HML96KHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Kt6FS_NpY5jc2Q_M9bqqYZLUQYsTFZI',
    appId: '1:662297242127:android:f8e66cbbda802509fed17a',
    messagingSenderId: '662297242127',
    projectId: 'lunastalaan',
    storageBucket: 'lunastalaan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU655PneKGgdzDvgz8sOI_CF1_LTBDWP8',
    appId: '1:662297242127:ios:7002a55520d54f34fed17a',
    messagingSenderId: '662297242127',
    projectId: 'lunastalaan',
    storageBucket: 'lunastalaan.appspot.com',
    iosBundleId: 'com.example.lunastalaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU655PneKGgdzDvgz8sOI_CF1_LTBDWP8',
    appId: '1:662297242127:ios:e3766cdf738a3027fed17a',
    messagingSenderId: '662297242127',
    projectId: 'lunastalaan',
    storageBucket: 'lunastalaan.appspot.com',
    iosBundleId: 'com.example.lunastalaan.RunnerTests',
  );
}
